#!/bin/bash
# Generate GTK CSS color variables for wlogout from the current Omarchy theme.
# Output: ~/.config/wlogout/colors.css (pywal-compatible @define-color names)

set -euo pipefail

COLORS_TOML="$HOME/.local/state/omarchy/current/theme/colors.toml"
OUT="$HOME/.config/wlogout/colors.css"

get() {
  sed -n "s/^$1 = \"\\(#[0-9a-fA-F]*\\)\".*/\\1/p" "$COLORS_TOML"
}

[[ -f $COLORS_TOML ]] || { echo "No Omarchy theme colors.toml at $COLORS_TOML" >&2; exit 1; }

background=$(get background)
foreground=$(get foreground)
darker_background=$(get darker_background)
muted=$(get muted)
red=$(get red)
green=$(get green)
yellow=$(get yellow)
blue=$(get blue)
magenta=$(get magenta)
cyan=$(get cyan)
bright_red=$(get bright_red)
bright_green=$(get bright_green)
bright_yellow=$(get bright_yellow)
bright_blue=$(get bright_blue)
bright_magenta=$(get bright_magenta)
bright_cyan=$(get bright_cyan)
bright_foreground=$(get bright_foreground)

cat > "$OUT" <<EOF
/* Generated by generate-colors.sh from Omarchy theme colors.toml - do not edit */

@define-color background $background;
@define-color foreground $foreground;

@define-color color0 $darker_background;
@define-color color1 $red;
@define-color color2 $green;
@define-color color3 $yellow;
@define-color color4 $blue;
@define-color color5 $magenta;
@define-color color6 $cyan;
@define-color color7 $foreground;
@define-color color8 $muted;
@define-color color9 $bright_red;
@define-color color10 $bright_green;
@define-color color11 $bright_yellow;
@define-color color12 $bright_blue;
@define-color color13 $bright_magenta;
@define-color color14 $bright_cyan;
@define-color color15 $bright_foreground;
EOF

echo "Wrote $OUT"
